openapi: '3.0.0'
info:
  title: 'laa-ccms-caab-api'
  version: '1.0.0'
paths:
  /applications:
    post:
      tags:
        - applications
      summary: 'Create Application'
      operationId: 'createApplication'
      requestBody:
        description: Create a application
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/applicationDetail'
      parameters:
        - name: 'Caab-user-Login-Id'
          in: header
          required: true
          schema:
            type: 'string'
          example: 'MARILYN@DESORANDCO.CO.UK'
      responses:
        '200':
          description: 'Successful operation'
        '400':
          description: 'Bad request'
        '401':
          description: 'Unauthorized'
        '404':
          description: 'Not found'
        '500':
          description: 'Internal server error'
components:
  schemas:
    costEntry:
      type: 'object'
      properties:
        requested_costs:
          type: 'number'
        cost_category:
          type: 'string'
        ebs_id:
          type: 'string'
        new_entry:
          type: 'boolean'
          default: true
        lsc_resource_id:
          type: 'string'
        resource_name:
          type: 'string'
    applicationDetail:
      type: 'object'
      properties:
        case_reference_number:
          type: 'string'
        provider:
          allOf:
            - $ref: "#/components/schemas/intDisplayValue"
          type: 'object'
          properties:
            case_reference:
              type: 'string'
          required:
            - id
        office:
          $ref: "#/components/schemas/intDisplayValue"
        supervisor:
          $ref: "#/components/schemas/stringDisplayValue"
        fee_earner:
          $ref: "#/components/schemas/stringDisplayValue"
        provider_contact:
          $ref: "#/components/schemas/stringDisplayValue"
        category_of_law:
          $ref: "#/components/schemas/stringDisplayValue"
          required:
            - id
        relation_to_linked_case:
          type: 'string'
        opponent_applied_for_funding:
          type: 'boolean'
        status:
          $ref: "#/components/schemas/stringDisplayValue"
        client:
          type: 'object'
          properties:
            first_name:
              type: 'string'
            surname:
              type: 'string'
            reference:
              type: 'string'
              required:
                - reference
        amendment:
          type: 'boolean'
        means_assessment_amended:
          type: 'boolean'
        merits_assessment_amended:
          type: 'boolean'
        cost_limit:
          type: 'object'
          properties:
            changed:
              type: 'boolean'
            at_time_of_merits:
              type: 'integer'
        application_type:
          $ref: "#/components/schemas/stringDisplayValue"
        devolved_powers:
          type: 'object'
          properties:
            used:
              type: 'boolean'
            date_used:
              type: 'string'
              format: 'date'
            contract_flag:
              type: 'string'
        merits_reassessment_required:
            type: 'boolean'
        lar_scope_flag:
            type: 'string'
        lead_proceeding_changed:
            type: 'boolean'
        correspondence_address:
          type: 'object'
          properties:
            no_fixed_abode:
              type: 'boolean'
            postcode:
              type: 'string'
            house_name_or_number:
              type: 'string'
            address_line_1:
              type: 'string'
            address_line_2:
              type: 'string'
            city:
              type: 'string'
            county:
              type: 'string'
            country:
              type: 'string'
            care_of:
              type: 'string'
            preferred_address:
              type: 'string'
        costs:
            type: 'object'
            properties:
              default_cost_limitation:
                type: 'number'
              granted_cost_limitation:
                type: 'number'
              requested_cost_limitation:
                type: 'number'
              cost_entries:
                type: 'array'
                items:
                  $ref: "#/components/schemas/costEntry"
      required:
        - case_reference_number
        - provider
        - category_of_law
        - client
    intDisplayValue:
      type: 'object'
      properties:
        id:
          type: 'integer'
        display_value:
          type: 'string'
    stringDisplayValue:
      type: 'object'
      properties:
        id:
          type: 'string'
        display_value:
          type: 'string'