DROP INDEX SYS_C0010978;
DROP INDEX SYS_C0011003;
DROP INDEX XXCCMS_COST_ENTRY_I1;
DROP INDEX SYS_C0010984;
DROP INDEX SYS_C0010985;
DROP INDEX XXCCMS_APPLICATION_I3;
DROP INDEX XXCCMS_APPLICATION_I2;

-- drop tables
DROP TABLE XXCCMS_APPLICATION;
DROP TABLE XXCCMS_LINKED_CASE;
DROP TABLE XXCCMS_COST_STRUCTURE;
DROP TABLE XXCCMS_COST_ENTRY;
DROP TABLE XXCCMS_ADDRESS;

DROP TABLE XXCCMS_PRIOR_AUTHORITY;
DROP TABLE XXCCMS_PROCEEDING;
DROP TABLE XXCCMS_PROCEEDING_OUTCOME;
DROP TABLE XXCCMS_OPPONENT;
DROP TABLE XXCCMS_CASE_OUTCOME;

-- drop sequence
DROP SEQUENCE XXCCMS_GENERATED_ID_S;