DROP INDEX SYS_C0010978;
DROP INDEX SYS_C0011003;
DROP INDEX SYS_C0010984;
DROP INDEX SYS_C0010985;
DROP INDEX XXCCMS_APPLICATION_I3;
DROP INDEX XXCCMS_APPLICATION_I2;

-- drop tables
DROP TABLE XXCCMS_APPLICATION;
DROP TABLE XXCCMS_COST_STRUCTURE;
DROP TABLE XXCCMS_ADDRESS;


-- drop sequence
DROP SEQUENCE XXCCMS_GENERATED_ID_S;