insert into XXCCMS_CASE_OUTCOME (ID,
                                 LSC_CASE_REFERENCE,
                                 PROVIDER_ID,
                                 PRE_CERTIFICATE_COSTS,
                                 LEGAL_COSTS,
                                 DISCHARGE_REASON,
                                 DISCHARGE_CASE_IND,
                                 CLIENT_CONTINUE_IND,
                                 OTHER_DETAILS,
                                 SUBMISSION_STATUS,
                                 POLL_TRANSACTION_ID,
                                 OFFICE_CODE,
                                 UNIQUE_FILE_NO,
                                 CREATED,
                                 CREATED_BY,
                                 MODIFIED,
                                 MODIFIED_BY)
values (1,
        'caseRef',
        'providerId1',
        100,
        200,
        'reason',
        'Y',
        'N',
        'other details',
        'status',
        'transId',
        'officeCode',
        'fileNo',
        SYSDATE,
        'testUser',
        SYSDATE,
        'testUser');

insert into XXCCMS_CASE_OUTCOME (ID,
                                 LSC_CASE_REFERENCE,
                                 PROVIDER_ID,
                                 PRE_CERTIFICATE_COSTS,
                                 LEGAL_COSTS,
                                 DISCHARGE_REASON,
                                 DISCHARGE_CASE_IND,
                                 CLIENT_CONTINUE_IND,
                                 OTHER_DETAILS,
                                 SUBMISSION_STATUS,
                                 POLL_TRANSACTION_ID,
                                 OFFICE_CODE,
                                 UNIQUE_FILE_NO,
                                 CREATED,
                                 CREATED_BY,
                                 MODIFIED,
                                 MODIFIED_BY)
values (2,
        'caseRef',
        'providerId2',
        100,
        200,
        'reason',
        'Y',
        'N',
        'other details',
        'status',
        'transId',
        'officeCode',
        'fileNo',
        SYSDATE,
        'testUser',
        SYSDATE,
        'testUser');


insert into XXCCMS_PROCEEDING_OUTCOME (ID,
                                       DATE_OF_ISSUE,
                                       DESCRIPTION,
                                       STAGE_END,
                                       RESOLUTION_METHOD,
                                       DATE_OF_FINAL_WORK,
                                       RESULT,
                                       RESULT_INFO,
                                       ALTERNATIVE_RESOLUTION,
                                       ADR_INFO,
                                       WIDER_BENEFITS,
                                       COURT_CODE,
                                       COURT_NAME,
                                       PROCEEDING_CASE_ID,
                                       STAGE_END_DISPLAY_VALUE,
                                       RESULT_DISPLAY_VALUE,
                                       OUTCOME_COURT_CASE_NO,
                                       FK_PROCEEDING_CASE_OUTCOME,
                                       CREATED,
                                       CREATED_BY,
                                       MODIFIED,
                                       MODIFIED_BY)
values (1,
        SYSDATE,
        'description',
        'stageEnd',
        'method',
        SYSDATE,
        'result',
        'result info',
        'alt res',
        'adr',
        'wider benefits',
        'code',
        'name',
        'procCaseId',
        'the stage end',
        'the result',
        'caseNo',
        1,
        SYSDATE,
        'testUser',
        SYSDATE,
        'testUser');

insert into XXCCMS_RECOVERY (ID,
                             AWARD_TYPE,
                             DESCRIPTION,
                             AWARD_AMT,
                             SOLICITOR_RECOVERY_AMT,
                             SOLICITOR_RECOVERY_DATE,
                             SOLICITOR_AMT_PAID_TO_LSC,
                             COURT_RECOVERY_AMT,
                             COURT_RECOVERY_DATE,
                             COURT_AMT_PAID_TO_LSC,
                             RECOVERED_AMT,
                             CLIENT_RECOVERY_DATE,
                             CLIENT_AMT_PAID_TO_LSC,
                             CLIENT_RECOVERY_AMT,
                             UNRECOVERED_AMT,
                             LEAVE_OF_COURT_REQD_IND,
                             OFFERED_AMT,
                             OFFER_DETAILS,
                             CREATED,
                             CREATED_BY,
                             MODIFIED,
                             MODIFIED_BY)
values (1,
        'type',
        'description',
        100,
        200,
        SYSDATE,
        500,
        600,
        SYSDATE,
        700,
        800,
        SYSDATE,
        900,
        1000,
        1100,
        'Y',
        1200,
        'details',
        SYSDATE,
        'testUser',
        SYSDATE,
        'testUser');

insert into XXCCMS_TIME_RECOVERY (ID,
                                  AWARD_TYPE,
                                  DESCRIPTION,
                                  TRIGGERING_EVENT,
                                  EFFECTIVE_DATE,
                                  TIME_RELATED_RECOVERY_DETAILS,
                                  AWARD_AMT,
                                  CREATED,
                                  CREATED_BY,
                                  MODIFIED,
                                  MODIFIED_BY)
values (1,
        'type',
        'description',
        'event',
        SYSDATE,
        'details',
        600,
        SYSDATE,
        'testUser',
        SYSDATE,
        'testUser');

insert into XXCCMS_COST_AWARD (ID,
                               AWARD_TYPE,
                               DESCRIPTION,
                               AWARDED_BY,
                               DATE_OF_ORDER,
                               AWARD_AMOUNT,
                               COURT_ASSESSMENT_STATUS,
                               PRECERTIFICATE_LSC_COST,
                               PRECERTIFICATE_OTHER_COST,
                               CERTIFICATE_COST_LSC,
                               CERTIFICATE_COST_MARKET,
                               INTEREST_AWARDED_RATE,
                               ORDER_DATE_SERVED,
                               INTEREST_START_DATE,
                               OTHER_DETAILS,
                               ADDRESS_LINE1,
                               ADDRESS_LINE2,
                               ADDRESS_LINE3,
                               UPDATE_ALLOWED_IND,
                               DELETE_ALLOWED_IND,
                               EBS_ID,
                               AWARD_CODE,
                               FK_COST_CASE_OUTCOME,
                               FK_COST_RECOVERY,
                               CREATED,
                               CREATED_BY,
                               MODIFIED,
                               MODIFIED_BY)
values (1,
        'type',
        'description',
        'person',
        SYSDATE,
        100,
        'status',
        200,
        300,
        500,
        600,
        700,
        SYSDATE,
        SYSDATE,
        'other details',
        'address line 1',
        'address line 2',
        'address line 3',
        0,
        1,
        'ebsId',
        'code',
        1,
        1,
        SYSDATE,
        'testUser',
        SYSDATE,
        'testUser');

insert into XXCCMS_FINANCIAL_AWARD (ID,
                                    AWARD_TYPE,
                                    DESCRIPTION,
                                    AWARDED_BY,
                                    DATE_OF_ORDER,
                                    AWARD_AMOUNT,
                                    STATUTORY_CHARGE_EXMP_REASON,
                                    AWARD_JUSTIFICATIONS,
                                    INTERIM_AWARD,
                                    DATE_ORDER_SERVED,
                                    OTHER_DETAILS,
                                    ADDRESS_LINE1,
                                    ADDRESS_LINE2,
                                    ADDRESS_LINE3,
                                    UPDATE_ALLOWED_IND,
                                    DELETE_ALLOWED_IND,
                                    EBS_ID,
                                    AWARD_CODE,
                                    FK_FINANCIAL_CASE_OUTCOME,
                                    FK_COST_RECOVERY,
                                    CREATED,
                                    CREATED_BY,
                                    MODIFIED,
                                    MODIFIED_BY)
values (1,
        'type',
        'description',
        'person',
        SYSDATE,
        100,
        'reason',
        'just',
        'interim',
        SYSDATE,
        'other details',
        'address line 1',
        'address line 2',
        'address line 3',
        0,
        1,
        'ebsId',
        'code',
        1,
        1,
        SYSDATE,
        'testUser',
        SYSDATE,
        'testUser');

insert into XXCCMS_LAND_AWARD (ID,
                               AWARD_TYPE,
                               DESCRIPTION,
                               AWARDED_BY,
                               DATE_OF_ORDER,
                               EQUITY,
                               AWARD_AMOUNT,
                               TITLE_NO,
                               VALUATION_AMT,
                               VALUATION_CRITERIA,
                               VALUATION_DATE,
                               DISPUTED_PERCENTAGE,
                               AWARDED_PERCENTAGE,
                               MORTGAGE_AMOUNT_DUE,
                               RECOVERY,
                               NO_RECOVERY_DETAILS,
                               STAT_CHARGE_EXEMPT_REASON,
                               LAND_CHARGE_EXEMPT_REASON,
                               REGISTRATION_REFERENCE,
                               RECOVERY_TIME_RELATED_FLAG,
                               ADDRESS_LINE1,
                               ADDRESS_LINE2,
                               ADDRESS_LINE3,
                               UPDATE_ALLOWED_IND,
                               DELETE_ALLOWED_IND,
                               EBS_ID,
                               AWARD_CODE,
                               FK_LAND_CASE_OUTCOME,
                               FK_LAND_RECOVERY,
                               CREATED,
                               CREATED_BY,
                               MODIFIED,
                               MODIFIED_BY)
values (1,
        'type',
        'description',
        'person',
        SYSDATE,
        100,
        200,
        'title',
        100,
        'crit',
        SYSDATE,
        10,
        20,
        100,
        'recovery',
        'no recovery',
        'reason',
        'land reason',
        'ref',
        'Y',
        'address line 1',
        'address line 2',
        'address line 3',
        0,
        1,
        'ebsId',
        'code',
        1,
        1,
        SYSDATE,
        'testUser',
        SYSDATE,
        'testUser');

insert into XXCCMS_OTHER_ASSET_AWARD (ID,
                                      AWARD_TYPE,
                                      DESCRIPTION,
                                      AWARDED_BY,
                                      DATE_OF_ORDER,
                                      AWARD_AMOUNT,
                                      VALUATION_AMT,
                                      VALUATION_CRITERIA,
                                      VALUATION_DATE,
                                      DISPUTED_PERCENTAGE,
                                      AWARDED_PERCENTAGE,
                                      RECOVERED_PERCENTAGE,
                                      DISPUTED_AMOUNT,
                                      AWARDED_AMOUNT,
                                      RECOVERED_AMOUNT,
                                      RECOVERY,
                                      NO_RECOVERY_DETAILS,
                                      STAT_CHARGE_EXEMPT_REASON,
                                      RECOVERY_TIME_RELATED_FLAG,
                                      UPDATE_ALLOWED_IND,
                                      DELETE_ALLOWED_IND,
                                      EBS_ID,
                                      AWARD_CODE,
                                      FK_OTHER_ASSET_CASE_OUTCOME,
                                      FK_OTHER_ASSET_RECOVERY,
                                      CREATED,
                                      CREATED_BY,
                                      MODIFIED,
                                      MODIFIED_BY)
values (1,
        'type',
        'description',
        'person',
        SYSDATE,
        100,
        100,
        'crit',
        SYSDATE,
        10,
        20,
        100,
        10,
        20,
        100,
        'recovery',
        'no recovery',
        'reason',
        'N',
        0,
        1,
        'ebsId',
        'code',
        1,
        1,
        SYSDATE,
        'testUser',
        SYSDATE,
        'testUser');

insert into XXCCMS_LIABLE_PARTY (ID,
                                 AWARD_TYPE,
                                 FK_COST_AWARD,
                                 FK_FINANCIAL_AWARD,
                                 FK_LAND_AWARD,
                                 FK_OTHER_ASSET_AWARD,
                                 FK_OPPONENT,
                                 CREATED,
                                 CREATED_BY,
                                 MODIFIED,
                                 MODIFIED_BY)
values (1,
        'type',
        1,
        1,
        1,
        1,
        3,
        SYSDATE,
        'testUser',
        SYSDATE,
        'testUser');